config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :customers

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Visible

  has_many :comments, dependent: :destroy

  # Sort
  default_scope { order('created_at DESC') }

  # Validate
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 5 }

  # def body_cannot_greater_than
  #   if body.length > 15
  #     errors.add(:message, 'cannot be greater than 15')
  #   end
  # end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  # attr_accessible :name, :status, :description, :code_type, :created_in_cell_id, :course_categories_id
  # VALID_STATUSES = ['public', 'private', 'archived']
  #
  # included do
  #   validates :status, inclusion: {in: VALID_STATUSES}
  # end
  #
  # def public_count
  #   where(status: 'public').count
  # end
  #
  # def archived?
  #   status == 'archived'
  # end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Visible
  belongs_to :article

  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
      # if params[:id]
      #   @articles = Article.where('id < ?', params[:id]).limit(3)
      # else
      #   @articles = Article.all
      # end
      # respond_to do |format|
      #   format.html
      #   format.js
      # end
      @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Post was successfully created"
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:notice] = "Post was successfully edited"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  attr_reader :article

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    # @comment = @article.comments.where('status == "publish"', params[:status])
    if @comment.save
      respond_to do |format|
        format.html {respond_to article_path @article, @comment}
        format.js   # -> create.js
      end
    else
      render @article
    end
    # redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    flash[:success] = "Comment deleted"
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    # @Customer= Customer.all.page(params[:page])

    @Customer = if params[:s]
               Customer.where('contactFirstName LIKE ?', "%#{params[:s]}%").page(params[:page])
               else
               @Customer= Customer.all.page(params[:page]).per(10)
                end
  end

  def new
    @Customer = Customer.new
  end

  def create
    # get new customer with customer params
    @Customer = Customer.new(customer_params)

    # if create new
    if @Customer.save
      # notice
      flash[:notice] = "New Customer was successfully created"
      redirect_to @Customer
    else
      render :new
    end
  end

  def show
    @Customer= Customer.find(params[:id])
  end

  def edit
    @Customer = Customer.find(params[:id])
  end

  def update
    @Customer = Customer.find(params[:id])

    if @Customer.update(customer_params)
      flash[:notice] = "Post was successfully edited"
      redirect_to @Customer
    else
      render :edit
    end
  end

  def destroy
    @Customer = Customer.find(params[:id])
    @Customer = Customer.destroy(params[:id])

    redirect_to customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:customerNumber, :customerName, :contactFirstName, :contactLastName, :phone, :city, :country, :term )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/views/articles/_article.html.haml
- @articles.each do |article|
  %div.article{"data-id" => "#{article.id}"}
    %h3.title-article
      =link_to article.title, article
    %p{:style => "margin-bottom: 55px;"}= article.body

app/views/articles/_form.html.haml
= form_for @article do |form|
  %div.form_dk
    = form.label :title
    %br/
    = form.text_field :title, :class => "input-title", require: true
  %div.form_dk
    = form.label :body
    %br/
    = form.text_area :body, require: true
    %br/
  %div
    = form.submit

app/views/articles/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Brand
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
    / /.navbar-collapse
  / /.container-fluid

app/views/articles/edit.html.haml
%h1.blog-title Edit Article
.main
  = render "form", article: @article

app/views/articles/index.html.haml
%h1.blog-title List Article
.main
  = button_to "New Article", new_article_path , method: :get, :class => "btn btn-primary"
  %br/
  %br/
  %br/
  -#%h2{:style => "font-size: 100%; margin-top: 0; padding-top: 0; padding-bottom: 20px;"} Latest
  .container
    = render 'articles/article'
  .result
  -# = paginate @article
  %p.text-center#view-more= link_to "View More", "#", :onclick => 'viewMore()', :remote => true
  -#%p.result

app/views/articles/new.html.haml
.main
  %h1.blog-title New Article
  - if @article.errors.any?
    %h2 The following errors prevented the article from saving:
    %ul.alert.alert-danger
      - @article.errors.full_messages.each do |msg|
        %li= msg
  .form
    = render "form", article: @article

app/views/articles/show.html.haml
%h1.blog-title= @article.title
.main
  %article
    %div.post-meta
      %i.updateTime= @article.created_at.strftime("%b %d,%Y")
    %p{:style => "margin-bottom: 55px;"}= @article.body
    = button_to "Edit", edit_article_path(@article) , method: :get, :class => "btn btn-primary"
    = button_to "Delete", @article , method: :delete, :class => "btn btn-danger", data: { confirm: "Are you sure?" }
  %br/
  %br/
  %br/

  -#%select.country
  -#  %option{value: "vn", selected: "Selected"} VN
  -#  %option{value: "sg"} SG
  -#  %option{value: "fr"} FR
  -#  %option{value: "us"} US
  -#-# = image_tag ('flags/vn.png')
  -#%span.flag


  .comment
    %h2 Comments
    .div-create= render @article.comments
    %h3 Add a comment:
    .ajax-form-create= render 'comments/form'

app/views/comments/_comment.html.haml
.comment-thread.root
  %p
    %strong= comment.commenter
  %p= comment.body

  %p.star= comment.status
  -# - @article.comments.each do |cmt|
  -#   %p= cmt.status
  -#%p= image_tag ('star.svg'), class: "commentStar"
  %p.commentStar
  %p
    = link_to 'Delete', [comment.article, comment], |
    method: :delete,                                       |
    data: { confirm: "Are you sure?" }                     |

app/views/comments/_form.html.haml
= form_for [@article, @article.comments.build], :html => {:class => 'form-comment'}, remote: true do |form|

  %p
    = form.label "Name"
    %br/
    = form.text_field :commenter, :id => "comment_name", require:true

  %p
    = form.label "Star: "

    = form.select(:status, options_for_select([['1 sao', '1'], ['2 sao', '2'], ['3 sao', '3'], ['4 sao', '4'], ['5 sao', '5']], ['1 sao', '1']), :id => "comment_status")

  %p
    = form.label "Comment"
    %br/
    = form.text_area :body, :id => "comment_content", placeholder: "Please enter your comment.", require:true
  %p
    = form.submit "Create Comment", :id => "commentSub"

app/views/customers/_customer.html.haml
%table.table.table-hover.container
  %thead.table-dark
    %th #
    %th FirstName
    %th LastName
    %th Phone
    %th
  - @Customer.each do |cus|
    %tr.customer{"data-id" => "#{cus.id}"}
      %th= cus.customerNumber
      %td= cus.contactFirstName
      %td= cus.contactLastName
      %td= cus.phone
      %td
        = button_to "Edit", edit_customer_path(cus) , :method => :get, :class => "btn btn-primary"
        = button_to "Delete", cus , :method => :delete, :class => "btn btn-danger", data: { confirm: "Are you sure?" }
        = button_to "Detail", cus , :method => :get, :class => "btn btn-light"

app/views/customers/_form.html.haml
= form_for @Customer do |cus|
  %div.form_dk
    = cus.label "ID"
    %br/
    = cus.text_field :customerNumber
  %div.form_dk
    = cus.label "Company Name"
    %br/
    = cus.text_field :customerName
  %div.form_dk
    = cus.label "First Name"
    %br/
    = cus.text_field :contactFirstName
  %div.form_dk
    = cus.label "Last Name"
    %br/
    = cus.text_field :contactLastName
    %br/
  %div.form_dk
    = cus.label "Phone"
    %br/
    = cus.text_field :phone
    %br/
  %div.form_dk
    = cus.label "City"
    %br/
    = cus.text_field :city
    %br/
  %div.form_dk
    = cus.label "Country"
    %br/
    = cus.text_field :country
    %br/
  %div
    = cus.submit

app/views/customers/edit.html.haml
%h1 Edit Customer
= form_for @Customer do |cus|
  %div
    = cus.label "First Name"
    %br/
    = cus.text_field :contactFirstName
  %div
    = cus.label "Last Name"
    %br/
    = cus.text_area :contactLastName
    %br/
  %div
    = cus.submit

app/views/customers/index.html.haml
.container
  = button_to "New Customer", new_customer_path, :method => :get, :class => "btn btn-primary"
%br
%br
%br
  = render "customers/customer"

.container= paginate @Customer, theme: 'twitter-bootstrap-3'

-#%p.text-center#view-more= link_to "View More", "#", :onclick => 'viewCustomer()', :remote => true

app/views/customers/new.html.haml
.main
  %h1.blog-title New Customer
  - if @Customer.errors.any?
    %h2 The following errors prevented the article from saving:
    %ul
      - @Customer.errors.full_messages.each do |msg|
        %li= msg
  = render "form", customer: @Customer

app/views/customers/show.html.haml
.main
  %label FirstName:
  %strong= @Customer.contactFirstName
  %br/

  %label LastName:
  %strong= @Customer.contactLastName
  %br/

  %label Phone:
  %strong= @Customer.phone
  %br/

  %label Company Name:
  %strong= @Customer.customerName
  %br/

  %label City:
  %strong= @Customer.city
  %br/

  %label Country:
  %strong= @Customer.country
  %br/

app/views/customers/test.html.erb
<% def msg(status) return "#{status}" end %>
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Create an Acccount</h2>
    <%= form_for @article do |f| %>
      <%= form_group_for f, :username, label: false do %>
        <div class="input-group">
          <span class="input-group-addon"><span class="fa fa-user fa-lg fa-fw"></span></span>
          <%= f.text_field :username, class: 'form-control', placeholder: 'UserName' %>
        </div>
      <% end %>
      <%= form_group_for f, :password, label: false  do %>
        <div class="input-group">
          <span class="input-group-addon"><span class="fa fa-key fa-lg fa-fw"></span></span>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
        </div>
      <% end %>
      <%= f.submit("Create Account", class:"btn btn-primary", data: {:confirm => msg('Do you want to create account?'), :disable_with => 'Creating'}) %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to "Home", root_path, class: "navbar-brand", id: "logo"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => customers_path} Customer
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
      = form_tag(customers_path, method: :get, :class => "d-flex") do
        = text_field_tag :s, params[:s], class: "form-control me-2", :type => "Search"
        = submit_tag 'Search', :class => "btn btn-outline-success"
        -#%input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        -#%button.btn.btn-outline-success{:type => "submit"} Search

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: 'defer'

  %body
    = render 'layouts/navigation'
    - flash.each do |name, msg|
      .alert.alert-success{:role => "success"}
        = msg
    = yield